### ISSUE TITLE
Changes to `_default_method`

### ISSUE THREAD

**Issue by mikeingold** [JuliaGeometry/MeshIntegrals.jl#146]
## Background

The `_default_method` utility function currently takes a `(::Geometry)` or `(::Type{<:Geometry})` as argument since it depended on the geometry being integrated. PR #139 potentially makes this obsolete by removing `Analytical` and making `FiniteDifference` the universal default.

## Ideas

I think the function should be renamed `_default_diff_method` for clarity.

Should this function continue to take geometry-information as an argument? We're not currently using that information, but it's possible that could change again in the future as more `DifferentiationMethod`s are implemented.

**Comment by JoshuaLampert** [comment]
I think it doesn't harm if `_default_method` takes a `geometry`. It shouldn't decrease performance, but allows for more flexibility in the future. I agree that renaming it to `_default_method` makes sense.
