### ISSUE TITLE
Implement benchmark test suite

### ISSUE THREAD

**Issue by mikeingold** [JuliaGeometry/MeshIntegrals.jl#21]
It would be nice to have a collection of benchmarks for integration methods that could be run to assess potential changes for performance impacts, identify performance regressions and opportunities for improvement, etc.

**Comment by mikeingold** [comment]
This GitHub Action package looks promising and has built-in Julia support

https://github.com/marketplace/actions/continuous-benchmark

**Comment by mikeingold** [comment]
@JoshuaLampert, have you seen/used [AirspeedVelocity.jl](https://github.com/MilesCranmer/AirspeedVelocity.jl)? It looks like this is actually what Miles used for the DynamicQuantities.jl reference above. I like how it automatically generates PR comments with benchmark comparisons vs the pull target.

**Comment by JoshuaLampert** [comment]
I think I had a brief look at it after I checked the link you send above for DynamicsQuantities, but I don't have any experience with it yet. I agree, it looks pretty nice.
